export const PROJECTS = [
  {
    cover: "/jackfruit/cover.png",
    title: "Jackfruit",
    images: ["/jackfruit/cover.png", "/jackfruit/1.png", "/jackfruit/2.png"],
    platform: "Website",
    titleColor: "#4263e2",
    description:
      "Jackfruit.ai is a platform that assists users in securing their dream jobs at top companies. We collaborated with Robert to create the platform using React, Node, AWS, GPT-4 and LinkedIn APIs. By integrating GPT-4, Jackfruit.ai offers users intelligent suggestions for job applications, message writing, LinkedIn connections, and more.",
    techStack: [
      "React JS",
      "Typescript",
      "Material UI",
      "tailwind CSS",
      "Styled-Components",
      "Google address autocomplete",
      "Node",
      "Express",
      "MongoDB",
    ],
  },
  {
    cover: "/tgl/cover.png",
    title: "The Gigs Live",
    description:
      "This app stands as a platform for artists and their fans to get connected, artists can host events on this platform and people can buy tickets for the same and artists can go live on particular date, users can chat with each other, users can send some tips($) to the artists to show them their love, so it helps fans to get more connected with artists and helps artists to get more fans.",
    images: ["/tgl/cover.png", "/tgl/1.png", "/tgl/2.png"],
    platform: "Mobile Application - Android & iOS",
    titleColor: "#ab037c",
    techStack: [
      "React Native",
      "Javascript",
      "Redux Saga",
      "Stripe",
      "Firebase Push-notifications",
      "Apple Pay",
    ],
  },
  {
    cover: "/zehmizeh/cover.png",
    title: "Zehmizeh",
    description:
      "Zehmizeh is a marketplace catering to Jewish talent. We were tasked with creating a beautiful design that reflected the company's desire for a simple UI/UX. We designed, developed, and launched the platform from scratch.",
    titleColor: "#f1b520",
    images: [
      "/zehmizeh/cover.png",
      "/zehmizeh/1.png",
      "/zehmizeh/2.png",
      "/zehmizeh/3.png",
      "/zehmizeh/4.png",
    ],
    platform: "Website",
    techStack: [
      "React JS",
      "React Bootstrap",
      "Styled-Components",
      "Javascript",
      "Stripe",
      "Node",
      "Express",
      "MongoDB",
    ],
  },
  {
    cover: "/trueview/cover.png",
    title: "Trueview",
    description:
      "Trueview app allows users to see which products they can consume. We've created a web application for them and IOS app as well.",
    titleColor: "#1c2bb9",
    images: [
      "/trueview/cover.png",
      "/trueview/1.png",
      "/trueview/2.png",
      "/trueview/3.png",
      "/trueview/4.png",
    ],
    platform: "Mobile Application - iOS",
    techStack: [
      "React Native",
      "Redux Toolkit",
      "Typescript",
      "Firebase social logins",
    ],
  },
  {
    cover: "/peerlyfe/cover.png",
    title: "Peerlyfe",
    description:
      "PeerLyfe is a social networking platform for private communities with many features like connecting, messaging, adding events, daily feeds, etc. We created a roadmap and converted it into a Figma design with an interactive prototype.",
    titleColor: "#844299",
    images: [
      "/peerlyfe/cover.png",
      "/peerlyfe/1.png",
      "/peerlyfe/2.png",
      "/peerlyfe/3.png",
      "/peerlyfe/4.png",
      "/peerlyfe/5.png",
    ],
    platform: "Website",
    techStack: [
      "React JS",
      "Typescript",
      "Material UI",
      "tailwind CSS",
      "Google address autocomplete",
      "Mobiscroll event calendar",
      "Node",
      "Express",
      "MongoDB",
    ],
  },
  {
    cover: "/ouro/cover.png",
    title: "Ouro",
    description:
      "Ouro is an app to buy and sell used shoes with each shoe getting sent to the Ouro warehouse for verification. We've developed the app from scratch and have also created an extremely robust admin portal to manage listings, products, users, transactions, and much more.",
    images: [
      "/ouro/cover.png",
      "/ouro/1.png",
      "/ouro/2.png",
      "/ouro/3.png",
      "/ouro/4.png",
      "/ouro/5.png",
    ],
    titleColor: "#35d283",
    platform: "Mobile Application - Android & iOS",
    techStack: ["React Native", "Redux Saga", "Stripe", "Apple pay"],
  },
  {
    cover: "/rigseye/cover.png",
    title: "Rigseye",
    description:
      "New website in React.js for RigsEye, a data solutions company.",
    images: ["/rigseye/cover.png", "/rigseye/1.png", "/rigseye/2.png"],
    platform: "Website",
    techStack: ["React JS", "Material UI", "tailwind CSS"],
    titleColor: "#00834D",
  },
  {
    cover: "/tandom/cover.png",
    title: "Tandm",
    description:
      "Tandm is an app to connect surfers through 'seshes'. We designed and developed this app in React Native and AWS.",
    images: [
      "/tandom/cover.png",
      "/tandom/1.png",
      "/tandom/2.png",
      "/tandom/3.png",
    ],
    titleColor: "#4aa9ad",
    platform: "Mobile Application - iOS",
    techStack: ["React Native", "Redux"],
  },
];
